# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Suppress compileSdk 35 warning with AGP 8.5
android.suppressUnsupportedCompileSdk=35

# Compose metrics (optional, useful for CI later)
# android.enableComposeCompilerMetrics=true
